# Generated by Django 2.0.2 on 2018-03-03 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Player', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='message',
            field=models.CharField(help_text="  It's nice gesture to add friendly message before actual battle began .. ^.^", max_length=300, verbose_name='Optional Message'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='to_user',
            field=models.ForeignKey(help_text='Please select Opponent', on_delete=django.db.models.deletion.CASCADE, related_name='Invitations_recived', to=settings.AUTH_USER_MODEL, verbose_name='User To Invite'),
        ),
    ]
